version: 2
updates:
- package-ecosystem: nuget
  directory: "/MyCalendar"
  schedule:
    interval: weekly
    time: "08:00"
    timezone: Europe/Vienna
  open-pull-requests-limit: 10
  target-branch: master
  labels:
  - dependencies
  - enhancement
  ignore:
  - dependency-name: Xamarin.AndroidX.Lifecycle.LiveData
    versions:
    - 2.3.0
    - 2.3.0.1
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.9.1
  - dependency-name: Xamarin.Google.Android.Material
    versions:
    - 1.3.0
  - dependency-name: Xamarin.AndroidX.MediaRouter
    versions:
    - 1.2.0.1
    - 1.2.1
    - 1.2.2
  - dependency-name: Xamarin.Essentials
    versions:
    - 1.6.0
