name: CI

on: [push, pull_request]

jobs:
  Practice:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Show what's in the directory
      run: |
        ls
    - name: Show what all is in the parent directory
      run: |
        cd ..
        ls
        
  Android:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Android
      run: |
        cd MyCalendar
        nuget restore
        cd MyCalendar.Android
        msbuild MyCalendar.Android.csproj /verbosity:normal /t:Rebuild /p:Configuration=Release
        
  iOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: iOS
      run: |
        cd MyCalendar
        nuget restore
        cd MyCalendar.iOS
        msbuild MyCalendar.iOS.csproj /verbosity:normal /t:Rebuild /p:Platform=iPhoneSimulator /p:Configuration=Release
