name: CI

on: [push, pull_request]

jobs:
  Android:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Android
      run: |
        cd MyCalendar\\MyCalendar\\MyCalendar
        nuget restore
        cd MyCalendar.Android
        msbuild MyCalendar.Android.csproj /verbosity:normal /t:Rebuild /p:Configuration=Debug
        
  iOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: iOS
      run: |
        cd MyCalendar\\MyCalendar\\MyCalendar
        nuget restore
        msbuild MyCalendar.iOS/MyCalendar.iOS.csproj /verbosity:normal /t:Rebuild /p:Platform=iPhoneSimulator /p:Configuration=Debug
