name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Android:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Android
      run: |
        cd MyCalendar
        nuget restore
        cd MyCalendar/MyCalendar.Android
        msbuild MyCalendar.Android.csproj /verbosity:normal /t:Rebuild /p:Configuration=Release
        
  iOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: iOS
      run: |
        cd MyCalendar
        nuget restore
        cd MyCalendar/MyCalendar.iOS
        msbuild MyCalendar.iOS.csproj /verbosity:normal /t:Rebuild /p:Platform=iPhoneSimulator /p:Configuration=Release
